import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdfaWQiOiI5NjE0IiwiY2hhdGJvdF9pZCI6IjY2YmYyNDllYWZlNTFiZGQ2MmFiZDc2OCIsInVzZXJfaWQiOiJwYXJha2gifQ.zBHGY-m6jlgtJ5qokxVFXOch63qmvID6a0E0CDFRmfc";
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script id= "chatbot-main-script" src="https://chatbot-embed.viasocket.com/chatbot-prod.js" embedToken={token}/>
    </html>
  );
}
